//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiDichVuChoThueXe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_ThuexeotoEntities : DbContext
    {
        public QL_ThuexeotoEntities()
            : base("name=QL_ThuexeotoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_BANGLAI> tbl_BANGLAI { get; set; }
        public virtual DbSet<tbl_KHACHHANG> tbl_KHACHHANG { get; set; }
        public virtual DbSet<tbl_LOAIXE> tbl_LOAIXE { get; set; }
        public virtual DbSet<tbl_PHIEUTHUE> tbl_PHIEUTHUE { get; set; }
        public virtual DbSet<tbl_THONGTINXE> tbl_THONGTINXE { get; set; }
        public virtual DbSet<User_Login> User_Login { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
    
        [DbFunction("QL_ThuexeotoEntities", "thanhtoan")]
        public virtual IQueryable<thanhtoan_Result> thanhtoan(string makh)
        {
            var makhParameter = makh != null ?
                new ObjectParameter("makh", makh) :
                new ObjectParameter("makh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<thanhtoan_Result>("[QL_ThuexeotoEntities].[thanhtoan](@makh)", makhParameter);
        }
    
        public virtual ObjectResult<ThongKePhieuThueTheoThoiGian_Result> ThongKePhieuThueTheoThoiGian(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKePhieuThueTheoThoiGian_Result>("ThongKePhieuThueTheoThoiGian", ngaybdParameter, ngayktParameter);
        }
    
        public virtual ObjectResult<TopXethue_Result> TopXethue(Nullable<System.DateTime> ngaybd, Nullable<System.DateTime> ngaykt)
        {
            var ngaybdParameter = ngaybd.HasValue ?
                new ObjectParameter("ngaybd", ngaybd) :
                new ObjectParameter("ngaybd", typeof(System.DateTime));
    
            var ngayktParameter = ngaykt.HasValue ?
                new ObjectParameter("ngaykt", ngaykt) :
                new ObjectParameter("ngaykt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TopXethue_Result>("TopXethue", ngaybdParameter, ngayktParameter);
        }
    }
}
