//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiDichVuChoThueXe
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_THONGTINXE
    {
        public string SoXe { get; set; }
        public string MaLoai { get; set; }
        public string TenXe { get; set; }
        public Nullable<int> DonGiaNgay { get; set; }
        public string ChuXe { get; set; }
        public Nullable<int> NamSX { get; set; }
    }
}
