//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiDichVuChoThueXe
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Login
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Login()
        {
            this.ChucVus = new HashSet<ChucVu>();
        }
    
        public int id { get; set; }
        public string TenDn { get; set; }
        public string Matkhau { get; set; }
        public string TenNhanVien { get; set; }
        public Nullable<long> SDT { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public Nullable<long> Luong { get; set; }
        public Nullable<int> ChucVu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChucVu> ChucVus { get; set; }
    }
}
